### ISSUE TITLE
Do something for once

### ISSUE THREAD

**Issue by agoodman1999** [Civiconnect/deployment-scripts#14]

**Comment by ABCodez** [comment]
what the freak dude, you try designing a dog judge page 😠😠😠😠😠😠😠

**Comment by agoodman1999** [comment]
issue remains open 🤔

**Comment by agoodman1999** [comment]
there is no evidence that something was done

**Comment by raykeating** [comment]
good first issue for sure

**Comment by agoodman1999** [comment]
i did something once enough for us both
